### PR TITLE
Hotfix/enhanced edit permissions

### PR DESCRIPTION
**Pull request by cmarfia**
Enhancements
- Removed white space
- Added layer of security to prevent the edit control from being displayed if the current user does not have edit rights
- Added layer of security to prevent the edit control from being displayed if manifest has disabled edit functionality
- Updated the API methods for Edit to return a 401 unauthorized if the manifest has editing disabled.
- Updated the API methods for lookups to have DNN View permission and perform a permissions check based on the content the user is trying to access.

### CODE REVIEW

**Comment by robsiera** [comment]
Thx Chris. Give us some time to review this. We're all on holiday at the moment.

**Comment by cmarfia** [comment]
No rush, let me know if any changes are required.

_Sent from my Lge LG-H910 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by sachatrauwaen** [comment]
I have some important remarks 

* Added layer of security to prevent the edit control from being displayed if the current user does not have edit rights 

This control work with clientside javascript, to be concequent this checks need to be done in webapi and handled by the javascript. With your changes all data access will be done twice.
And because nothing is done in the webforms, no securrity issues exist there.

* Added layer of security to prevent the edit control from being displayed if manifest has disabled edit functionality. 
This normalilly not occurs, it need to be handled by the template.
If not handled b the template, Not authorised need to be displayed in place of redirect. To give better feedback.

* Updated the API methods for Edit to return a 401 unauthorized if the manifest has editing disabled.

Ok, but some users with view permissions and special role configured in manifest, need to add and edit there own items.

* Updated the API methods for lookups to have DNN View permission and perform a permissions check based on the content the user is trying to access.

This are not really edit apis, but may be restricted for users with edit permissions.

So many things need to be adapted.
If you want we can discused this more in detail on a skype meeting.

**Comment by cmarfia** [comment]
@sachatrauwaen, 

Will gladly hop on a skype call to discuss further. This might end up being something specific to my use case, but if there is something that could benefit the core product it is worth reviewing further.

**Comment by sachatrauwaen** [comment]
@cmarfia It sound like some misunderstanding of me or you.
I think it further reviewing worth.

You can skype me on id : satrabel so we can reviewed together.

**Pull request closed without merging**
