### PR TITLE
Enable the ability to have manifests pulled from Skin level templates like portal templates.

### PR DESCRIPTION
**Pull request by cmarfia**

### CODE REVIEW

**Comment by sachatrauwaen** [comment]
Hi cmarfia, Thanks for this pull request.

If i understand right, you add the ability to use templates from the skin folder for templates with manifest. 
This was not yet implemented.

Is that rigtht ?

**Comment by cmarfia** [comment]
@sachatrauwaen, 

That is correct. 

I added the ability for manifests to be read in for templates placed in the skin folders. My latest commit fixed an issue discovered when pulling data from another datasource.

This should be working code, let me know if you run into any issues, I will be happy to fix.

**Comment by sachatrauwaen** [comment]
@cmarfia 

Can you tell what the indend is of this line ?

            if (otherModuleTemplate != null && !otherModuleTemplate.PhysicalFilePath.Contains(HostingEnvironment.MapPath(GetSkinTemplateFolder(portalSettings, moduleSubDir))))

**Comment by cmarfia** [comment]
@sachatrauwaen, 

That line is to prevent the same template from being added to the drop down list twice when using skin level templates and pulling data from another module.

**Comment by sachatrauwaen** [comment]
@cmarfia 

I find some issues with the template selection from skinfolder and othermodules.

The idea is that when you select a othermodule, the list of template of the dropdownlist contains only template from the folder of the othermodule template folder.

Can you check if my changes works for you.

**Pull request merged**
