### PR TITLE
Added support the DNNConnect.CKEditorProvider.

### PR DESCRIPTION
**Pull request by cmarfia**

### CODE REVIEW

**Comment by sachatrauwaen** [comment]
Hi,

Thanks a lot for this contribution.
I want to merge this, but i seen that you have done the changes in master branch.

And we always works in develop branch. And only put in the master branch when we release a new release. (We use Git flow from source tree)

So for the future please make pullrequest in the develop branch.

For this pull request, 2 possibilities 
1) you make a new pullrequest in develop (without removing the forreign key)
2) i do a manual merge in develop branch

Wath do you prefer ?

**Comment by cmarfia** [comment]
I will rollback my changes and create a pull request to the correct branch.

**Comment by sachatrauwaen** [comment]
ok, nice. Thanks for that.

**Comment by sachatrauwaen** [comment]
The fix for using DNNConnect Ckeditor if present is manually integrated

**Pull request closed without merging**
